abraworld/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music_library.urls')),
]

music_library/urls.py
from django.conf.urls import url

from music_library import views


app_name = 'music'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^albums$', views.AlbumsView.as_view(), name='albums'),
    url(r'^albums/(?P<pk>[0-9]+)$', views.AlbumView.as_view(), name='album'),
    # url(r'^albums/(?P<album_id>[0-9]+)/tracks$', views.TracksView.as_view(), name='tracks'),
    # url(r'^albums/(?P<album_id>[0-9]+)/tracks/(?P<track_id>[0-9]+)$', views.TrackView.as_view(), name='track'),
    url(r'^albums/(?P<album_id>[0-9]+)/tracks/new$', views.add_track, name='add_track'),

]

music_library/models.py
from __future__ import unicode_literals

from datetime import datetime, timedelta

from django.db import models


# Create your models here.
from django.utils.encoding import python_2_unicode_compatible


class NameMixin(object):
    @property
    def short_name(self):
        if len(self.name) > 10:
            return self.name[:8] + '...'
        else:
            return self.name

    def was_published_recently(self):
        return datetime.utcnow().date() >= self.publish_at >= (datetime.utcnow() - timedelta(days=1)).date()

    was_published_recently.admin_order_field = 'publish_at'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible
class Album(models.Model, NameMixin):
    name = models.CharField(max_length=128)
    publish_at = models.DateField()

    def __str__(self):
        return '#{0} {1}'.format(self.id, self.short_name)


@python_2_unicode_compatible
class Track(models.Model, NameMixin):
    name = models.CharField(max_length=256)
    extension = models.CharField(max_length=8)
    size = models.BigIntegerField()
    publish_at = models.DateField()
    album = models.ForeignKey(Album)

    def __str__(self):
        return '#{0} {1}'.format(self.id, self.short_name)

music_library/views.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views import generic

from music_library.models import Album, Track


def index(request):
    context = {
        'latest_albums_list': Album.objects.all()[:5]
    }
    return render(request, 'music_library/index.html', context)


class AlbumsView(generic.ListView):
    template_name = 'music_library/albums.html'
    context_object_name = 'latest_albums_list'

    def get_queryset(self):
        return Album.objects.order_by('-publish_at').all()[:5]


class AlbumView(generic.DetailView):
    template_name = 'music_library/album.html'
    model = Album


class TracksView(generic.ListView):
    template_name = 'music_library/trucks.html'
    context_object_name = 'tracks'

    def get_queryset(self):
        return Track.objects.all()


class TrackView(generic.DetailView):
    template_name = 'music_library/track.html'
    model = Track


def add_track(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        track = album.track_set.create(
            name=request.POST['name'],
            extension=request.POST['extension'],
            size=1024,
            publish_at=datetime.utcnow()
        )
    except (KeyError, ):
        return render(request, 'music_library/album.html', {'album': album, 'error_message': 'invalid fields'})
    return HttpResponseRedirect(reverse('music:album', args=(album_id,)))

music_library/templates/music_library/album.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album #{{ album.id }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'music_library/style.css' %}" />
</head>
<body>
<p>Album #{{ album.id }}</p>
<p>Name: {{ album.name }}</p>
<p>Publish Date: {{ album.publish_at }}</p>
<p>Trucks:</p>
<ul>
{% for track in album.track_set.all %}
    <li><a href="#">{{ track.name }}.{{ track.extension }}</a></li>
{% endfor %}
</ul>

<h4>Add Track:</h4>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'music:add_track' album.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" value="" /><br/>
    <input type="text" name="extension" value="" /><br/>
    <input type="submit" value="Add" />
</form>

</body>
</html>

music_library/templates/music_library/albums.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'music_library/style.css' %}" />
</head>
<body>
{% for album in albums %}

{% endfor %}
</body>
</html>

music_library/templates/music_library/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_albums_list %}
    <ul>
    {% for album in latest_albums_list %}
        <li><a href="albums/{{ album.id }}">{{ album.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No albums are available.</p>
{% endif %}
</body>
</html>